### ISSUE TITLE
Make search bar to work

### ISSUE THREAD

**Issue by dahlia** [planetarium/libplanet-explorer-frontend#5]
Although there is a top search bar, but it does not work at all.  We should implement some search patterns, e.g.:

- [x] Block hash (`ff64cab33a6bca4e7e7cdff4d654fccd617792d49510e8492b81af8d4bcad36d`)
- [ ] Block index (like `#123`?)
- [x] #10 TxID (`ff64cab33a6bca4e7e7cdff4d654fccd617792d49510e8492b81af8d4bcad36d` → this and block hash are both a SHA-256 hexadecimal digest; we need to distinguish two)
- [ ] #9 Account address (`0x561329477ECB990d16a0aB60067d81676d36EE69`)

**Comment by channprj** [comment]
It's difficult to distinguish between TxID and Block hash. Both use SHA256. I think federated search page is one of option. Also, we can add dropdown in front of the search box.


## Reference

- TxID: https://github.com/planetarium/libplanet/blob/master/Libplanet/Tx/Transaction.cs#L172
- Block hash: https://github.com/planetarium/libplanet/blob/master/Libplanet/Hashcash.cs#L85
